import { WorkspaceReport } from '../model/report';

export function reportHtml(report: WorkspaceReport, nonce: string): string {
  const data = JSON.stringify(report).replace(/</g, '\\u003c').replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029');
  return `<!doctype html><html><head><meta charset="UTF-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'nonce-${nonce}'; script-src 'nonce-${nonce}';"><style nonce="${nonce}">
body{font-family:var(--vscode-font-family);color:var(--vscode-foreground);background:var(--vscode-editor-background);padding:24px;max-width:1400px;margin:auto}h1{font-size:24px}h2{margin-top:28px;border-bottom:1px solid var(--vscode-panel-border);padding-bottom:8px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:8px}.metric{padding:10px;background:var(--vscode-textCodeBlock-background);border:1px solid var(--vscode-panel-border)}.value{font-size:21px;font-weight:600;display:block}button{font:inherit;color:var(--vscode-textLink-foreground);background:none;border:0;padding:0;cursor:pointer;text-align:left}table{border-collapse:collapse;width:100%;display:block;overflow:auto}td,th{text-align:left;padding:7px;border-bottom:1px solid var(--vscode-panel-border);vertical-align:top;max-width:420px}.complex{color:var(--vscode-charts-yellow)}.architecture{white-space:pre-wrap;background:var(--vscode-textCodeBlock-background);padding:12px}.muted{opacity:.75}
</style></head><body><h1>Sealevel Insight Audit Cockpit</h1><div id="app"></div><script nonce="${nonce}">
const vscode=acquireVsCodeApi();const report=${data};const app=document.getElementById('app');
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const open=location=>'<button data-location="'+encodeURIComponent(JSON.stringify(location))+'">'+esc(location.label||location.name||location.type||'open source')+'</button>';
const metric=(name,value)=>'<div class="metric">'+esc(name)+'<span class="value">'+esc(value)+'</span></div>';
const table=(headers,rows,empty)=>'<table><tr>'+headers.map(x=>'<th>'+esc(x)+'</th>').join('')+'</tr>'+(rows.map(row=>'<tr>'+row.map(x=>'<td>'+x+'</td>').join('')+'</tr>').join('')||'<tr><td colspan="'+headers.length+'">'+esc(empty)+'</td></tr>')+'</table>';
const s=report.summary,manifest=report.auditManifest;
const summary=[['Programs',report.programs.length],['Rust files',s.rustFiles],['LOC',s.loc],['nSLOC',s.codeLoc],['Functions',s.functions],['Instructions',s.instructions],['Dossiers',manifest?.scope.dossiers||0],['State flows',manifest?.scope.stateFlows||0],['PDAs',s.pdas],['CPIs',s.cpis],['PDA-signed CPIs',s.pdaSignedCpis]];
const audit='<h2>Audit Manifest</h2><p>Mode: '+esc(manifest?.analysisMode||'unavailable')+'. This is evidence-backed audit scope, not a vulnerability verdict.</p>'+table(['Review queue','Score','Coverage','Why'],(manifest?.reviewQueue||[]).slice(0,100).map(x=>[open({label:x.program+'::'+x.instruction,...x.location}),esc(x.score),x.complete?'Resolved':'Incomplete',esc(x.reasons.join('; '))]),'No instructions extracted.')+'<p>Unresolved: '+(manifest?.unresolved.incompleteInstructionDossierIds.length||0)+' incomplete dossiers, '+(manifest?.unresolved.unknownOrDynamicCallIds.length||0)+' unknown/dynamic calls, '+(manifest?.unresolved.dynamicCpiIds.length||0)+' dynamic CPIs, '+(manifest?.unresolved.idlMismatchItems.length||0)+' IDL differences.</p>';
const dossierTable=p=>'<h3>Instruction Dossiers</h3>'+table(['Instruction','Reachability','Accounts / state','CPIs','Cross-package','Unresolved evidence','Evidence paths','PDAs','Lifecycle','Review'],(p.instructionDossiers||[]).map(d=>[open({label:d.name,...d.location}),d.reachability.complete?'Resolved':esc('Incomplete: '+d.reachability.incompleteReasons.join('; ')),d.accounts.length+' accounts<br>'+d.stateTypeIds.length+' state types',d.cpis.map(c=>esc(c.operation||c.target||'dynamic')+(c.pdaSigned?' (signed)':'')).join('<br>'),d.crossPackageSurfaces.map(x=>esc(x.program)+' · '+x.functions.length+' functions · '+x.cpiIds.length+' CPIs · '+x.pdaIds.length+' PDAs').join('<br>')||'none',d.reachability.unresolvedCallDetails.map(x=>'<strong>'+esc(x.expression)+'</strong>: '+esc(x.reason)+(x.candidates.length?'<br><span class="muted">Candidates: '+esc(x.candidates.join(', '))+'</span>':'')).join('<br>')||'none',(d.reachabilityWitnesses||[]).map(x=>'<strong>'+esc(x.targetKind+' '+x.targetProgram+'::'+x.targetId)+'</strong><br>'+esc(x.functionPath.join(' → '))+(x.callPath.length?'<br><span class="muted">'+esc(x.callPath.join(' → '))+'</span>':'')).join('<br>')||'none',d.pdas.map(x=>esc(x.seeds.join(', ')||'unresolved')+(x.usedAsSigner?' (signer)':'')).join('<br>'),'init '+d.semanticSites.initialization.length+' · realloc '+d.semanticSites.realloc.length+' · close '+d.semanticSites.close.length+' · writes '+d.semanticSites.dataMutation.length,esc(d.reviewComplexity?.score||0)]),'No externally reachable instructions extracted.');
const program=p=>{const cfg=p.conditionalCompilation||{};const functions=[...p.functions].sort((a,b)=>b.complexity-a.complexity);const graph=(p.architecture?.edges||[]).map(e=>{const from=p.architecture.nodes.find(n=>n.id===e.source)?.label||e.source;const to=p.architecture.nodes.find(n=>n.id===e.target)?.label||e.target;return esc(from)+' --'+esc(e.type)+'--> '+esc(to)}).join('\\n');return '<h2>Program: '+esc(p.name)+'</h2><p>Kind: '+esc(p.packageKind||'unknown')+'<br>Conditional compilation: '+(cfg.inactiveItems||0)+' excluded, '+(cfg.unknownItems||0)+' unknown; feature knowledge '+esc(cfg.featureKnowledge||'unknown')+(cfg.enabledFeatures?.length?' ('+esc(cfg.enabledFeatures.join(', '))+')':'')+'<br>'+p.frameworkEvidence.map(f=>esc(f.framework)+' ('+Math.round(f.confidence*100)+'%): '+f.evidence.map(e=>esc(e.description)).join(', ')).join('<br>')+'</p>'+dossierTable(p)+'<h3>Functions</h3>'+table(['Name','LOC','Complexity','cfg','CPI','PDA','Instruction'],functions.map(f=>[open({label:f.name,...f.location}),f.lines,'<span class="'+(f.complexity>=10?'complex':'')+'">'+f.complexity+'</span>',esc(f.cfgStatus||'active'),p.securitySurface.cpiSites.filter(c=>c.functionName===f.name).length,p.securitySurface.pdaSites.filter(x=>x.enclosingFunction===f.name).length,p.instructions.some(i=>i.functionName===f.name)?'yes':'']),'No functions extracted.')+'<h3>Architecture</h3><div class="architecture">'+(graph||'No relationships extracted.')+'</div>'};
const profile=report.compilationProfile;const profileHtml='<h2>Compilation Profile</h2><p>Target: '+esc(profile?.target||'not specified')+'; mode: '+esc(profile?.mode||'normal')+'; cfg knowledge: '+esc(profile?.cfgKnowledge||'implicit/partial')+'; cfg options: '+esc(profile?.cfgOptions?.join(', ')||'none')+'; debug assertions: '+esc(profile?.debugAssertions===undefined?'unknown':profile.debugAssertions?'enabled':'disabled')+'.</p>';
app.innerHTML='<h2>Overview</h2><div class="grid">'+summary.map(x=>metric(x[0],x[1])).join('')+'</div>'+profileHtml+audit+report.programs.map(program).join('')+'<h2>Files</h2>'+table(['File','LOC','nSLOC','Functions','Unsafe'],report.files.map(f=>[open({label:f.uri,uri:f.uri,startLine:1,startColumn:0,endLine:1,endColumn:0}),f.lines,f.codeLines,f.functions,f.unsafeBlocks]),'No Rust files.')+(report.diagnostics.length?'<h2>Diagnostics</h2><pre>'+report.diagnostics.map(esc).join('\\n')+'</pre>':'');
document.querySelectorAll('[data-location]').forEach(button=>button.addEventListener('click',()=>{const location=JSON.parse(decodeURIComponent(button.dataset.location));delete location.label;vscode.postMessage({type:'openSource',location})}));
</script></body></html>`;
}
